CREATE TABLE IF NOT EXISTS venue_check_ins (
  id UUID PRIMARY KEY NOT NULL DEFAULT GEN_RANDOM_UUID(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  venue_id UUID NOT NULL,
  checked_in_at TIMESTAMPTZ NOT NULL
);
